"""Data models for the scalping bot."""

from dataclasses import dataclass, field
from enum import Enum
from typing import Optional
import time


class Side(Enum):
    LONG = "long"
    SHORT = "short"


@dataclass
class IndicatorSnapshot:
    """Snapshot of all indicator values at a point in time."""
    ema_fast: float
    ema_slow: float
    rsi: float
    bb_upper: float
    bb_middle: float
    bb_lower: float
    vwap: float
    volume_ratio: float          # current vol / avg vol
    orderbook_imbalance: float   # positive = bid-heavy, negative = ask-heavy
    close_price: float
    timestamp: float
    # v3.0 advanced fields
    macd: float = 0.0
    macd_signal: float = 0.0
    macd_histogram: float = 0.0
    atr: float = 0.0
    atr_pct: float = 0.0          # ATR as % of price
    rsi_prev: float = 50.0
    price_prev: float = 0.0
    bb_width: float = 0.0         # BB squeeze detection
    volume_delta: float = 0.0     # buy vol - sell vol estimate
    consecutive_green: int = 0
    consecutive_red: int = 0
    htf_ema_fast: float = 0.0     # higher timeframe EMA (25-period as 5m proxy)
    htf_ema_slow: float = 0.0     # higher timeframe EMA (65-period as 5m proxy)


@dataclass
class Signal:
    """A trade signal generated by the strategy."""
    side: Side
    score: float
    indicators: IndicatorSnapshot
    recommended_leverage: int = 15   # dynamic leverage recommendation
    timestamp: float = field(default_factory=time.time)


@dataclass
class Position:
    """An open position being managed."""
    side: Side
    entry_price: float
    quantity: float
    leverage: int
    stop_loss: float
    take_profit: float
    trailing_stop_price: Optional[float] = None
    trailing_stop_active: bool = False
    highest_price: float = 0.0
    lowest_price: float = 999_999_999.0
    entry_time: float = field(default_factory=time.time)
    pnl_unrealized: float = 0.0
    atr_pct: float = 0.0  # v4.0: stored for ATR-based trailing stop


@dataclass
class TradeRecord:
    """Record of a completed trade for the journal."""
    timestamp: float
    side: str
    entry_price: float
    exit_price: float
    quantity: float
    leverage: int
    pnl: float
    pnl_pct: float
    exit_reason: str  # "tp", "sl", "trailing", "manual", "daily_limit", "shutdown"
    duration_sec: float
    score: float


@dataclass
class OrderBookSnapshot:
    """Snapshot of the order book top levels."""
    bids: list  # [(price, qty), ...]
    asks: list  # [(price, qty), ...]
    timestamp: float
    bid_volume: float = 0.0
    ask_volume: float = 0.0
    imbalance: float = 0.0  # (bid_vol - ask_vol) / (bid_vol + ask_vol)

    def compute_imbalance(self) -> None:
        self.bid_volume = sum(qty for _, qty in self.bids) if self.bids else 0.0
        self.ask_volume = sum(qty for _, qty in self.asks) if self.asks else 0.0
        total = self.bid_volume + self.ask_volume
        self.imbalance = (self.bid_volume - self.ask_volume) / total if total > 0 else 0.0
